# pitch-basic-auth.js (docs backlog item, 2026-09-03) used to hardcode
# its Basic Auth credential in plaintext, sitting in this **public**
# repo's working tree - never actually committed (the user's own
# explicit 3-day deferral, 2026-08-31 -> 2026-09-03), but the deferral
# window has closed. This replaces it: the credential is generated by
# Terraform's own `random` provider (mirrors hr_service_account.tf/
# im_service_account.tf/pop_gl_service_account.tf's existing pattern
# for every other generated secret in this config - nobody, including
# an AI agent, ever needs to see or type the plaintext), stored in
# Secrets Manager, and templated into the CloudFront Function's code
# at `terraform apply` time via templatefile() - the function itself
# still can't call Secrets Manager at *request* time (CloudFront
# Functions have no network access at all, unlike Lambda@Edge), so the
# value has to be baked in at deploy time either way; this just moves
# *where* that baking happens from "a human's editor" to Terraform.
#
# **Deliberately NOT wired into any `function_association` yet** -
# which path/distribution this should actually gate was never decided
# (the old file lived in this directory for that eventual purpose, but
# nothing in this config ever referenced it - confirmed by grep before
# writing this). Flagged back to the user rather than guessed.

resource "random_password" "pitch_basic_auth" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "pitch_basic_auth" {
  name        = "${var.project_name}/${var.environment}/pitch-basic-auth"
  description = "Basic Auth credential gating the Prodeo Capital pitch deck (pitch-basic-auth.js.tftpl CloudFront Function)."
}

resource "aws_secretsmanager_secret_version" "pitch_basic_auth" {
  secret_id = aws_secretsmanager_secret.pitch_basic_auth.id
  secret_string = jsonencode({
    username = "investor"
    password = random_password.pitch_basic_auth.result
  })
}

resource "aws_cloudfront_function" "pitch_basic_auth" {
  name    = "${var.project_name}-pitch-basic-auth"
  runtime = "cloudfront-js-2.0"
  comment = "Gates the Prodeo Capital pitch deck behind Basic Auth."
  publish = true
  code = templatefile("${path.module}/pitch-basic-auth.js.tftpl", {
    expected_auth = base64encode("investor:${random_password.pitch_basic_auth.result}")
  })
}
